name: heroes
description: An empty Aqueduct application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=1.2.0 <2.0.0"

dependencies:
  aqueduct: 3.3.0+1
<<<<<<< HEAD
  browser: "^0.10.0+2"
  redstone: "^0.6.8"

=======
<<<<<<< Updated upstream
  redstone: any
=======
>>>>>>> Stashed changes
>>>>>>> 10184500416

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0